# Generated by Django 5.0.6 on 2024-07-05 15:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='home.tourcategory'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerario',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='linkFlyer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Flyer'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='linkPdf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Pdf'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='linkWord',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Word'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourDestino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_foreign', to='home.destino', verbose_name='Destino'),
        ),
    ]
