# Generated by Django 5.0.6 on 2024-08-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_linkflyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duracion',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Duracion del Tour, 0 o 1 = no aparecera'),
        ),
    ]
