# Generated by Django 5.0.6 on 2024-08-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_categories_alter_tour_itinerario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='linkFlyer',
        ),
    ]
