# Generated by Django 5.1.2 on 2024-11-02 01:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='blog',
            name='featuredImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='categoryblog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.categoryblog'),
        ),
        migrations.AddField(
            model_name='categoryblogpage',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoryblog', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categoryblogpage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='blog.CategoryBlogPage', to='blog.categoryblog'),
        ),
    ]
