# Generated by Django 5.0.6 on 2024-08-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0003_dias_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='isCampaing',
            field=models.BooleanField(default=False, verbose_name='Campaña'),
        ),
    ]
