# Generated by Django 5.0.6 on 2024-08-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('home', '0012_blogpage_articulosrecomendados'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='blog',
            name='featuredImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage', verbose_name='Thumbnail'),
        ),
    ]
