# Generated by Django 5.0.6 on 2024-09-02 16:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_background_blog_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Poner aqui la descripcion del Post o poner una invitacion para leer mas', max_length=300, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Cuerpo de texto, Post'),
        ),
    ]
