# Generated by Django 5.0.6 on 2024-06-24 23:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=255, verbose_name='Numero Formato +x xxxxxxx o Texto de Boton ')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('link', models.CharField(max_length=300, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('redLet', models.CharField(max_length=50, verbose_name='Letra Roja')),
                ('grayLet', models.CharField(max_length=50, verbose_name='Letra Gris')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('answer', wagtail.fields.RichTextField(verbose_name='Respuesta')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('carouselTitulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('carouselDuracion', models.CharField(max_length=30, verbose_name='Duracion')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('paqueteTitulo', models.CharField(max_length=30, verbose_name='Subtitulo Paquetes')),
                ('destinoTitulo', models.CharField(max_length=30, verbose_name='Subtitulo Destinos')),
                ('formularioTitulo', models.CharField(max_length=75, verbose_name='Titulo Formulario')),
                ('formularioSubtitulo', models.CharField(max_length=75, verbose_name='Subtitulo Formulario')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subTitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('parrafo', wagtail.fields.RichTextField(verbose_name='Parrafo')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('numeroRuc', models.CharField(max_length=100, verbose_name='Numero de Ruc')),
                ('nombreComercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('certificadoAutorizacion', models.CharField(max_length=100, verbose_name='Certificado de Autorizacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=50, verbose_name='Nombre del valor')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
