# Generated by Django 5.0.6 on 2024-09-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='puv',
            field=models.CharField(max_length=350, verbose_name='Promesa Unica de Valor'),
        ),
    ]
