# Generated by Django 5.0.6 on 2024-06-24 23:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='destino',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paquete.cloudinaryimage', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='gallerycarousel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='gallerycarousel',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryInicio', to='home.inicio'),
        ),
        migrations.AddField(
            model_name='faq',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqInicio', to='home.inicio'),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imageParrafo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticasNosotros', to='home.nosotros'),
        ),
        migrations.AddField(
            model_name='certificados',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificadosNosotros', to='home.nosotros'),
        ),
        migrations.AddField(
            model_name='partners',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='partners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnersNosotros', to='home.nosotros'),
        ),
        migrations.AddField(
            model_name='valores',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paquete.cloudinaryimage'),
        ),
        migrations.AddField(
            model_name='valores',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoresNosotros', to='home.nosotros'),
        ),
    ]
