# Generated by Django 5.0.6 on 2024-06-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paquete.cloudinaryimage', verbose_name='Imagen de Fondo'),
        ),
    ]
