# Generated by Django 5.0.6 on 2024-09-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_nosotros_puv'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='middleMensaje',
            field=models.CharField(default='aaa', max_length=350, verbose_name='Mensaje Intermedio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='middleMensajeTitle',
            field=models.CharField(default='aaa', max_length=350, verbose_name='Mensaje Intermedio Subtitulo'),
            preserve_default=False,
        ),
    ]
