# Generated by Django 5.0.6 on 2024-07-04 15:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
