# Generated by Django 5.0.6 on 2024-06-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataNumero',
            new_name='Informacion',
        ),
    ]
