# Generated by Django 5.0.6 on 2024-09-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nosotros_middlemensaje_nosotros_middlemensajetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='puvName',
            field=models.CharField(max_length=150, verbose_name='Promesa Unica de Valor Nombre'),
        ),
    ]
