# Generated by Django 5.0.6 on 2024-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallerycarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='destinoTitulo',
            field=models.CharField(default='', max_length=30, verbose_name='Subtitulo Destinos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicio',
            name='paqueteTitulo',
            field=models.CharField(default='', max_length=30, verbose_name='Subtitulo Paquetes'),
            preserve_default=False,
        ),
    ]
