# Generated by Django 5.0.6 on 2024-07-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_global_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycarousel',
            name='carouselButtonName',
            field=models.CharField(default='Ver Paquete', max_length=50, verbose_name='Texto del Boton'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycarousel',
            name='carouselLink',
            field=models.CharField(default='aoeaeo', max_length=50, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerycarousel',
            name='carouselDuracion',
            field=models.CharField(default=' ', max_length=30, verbose_name='Duracion'),
        ),
    ]
