# Generated by Django 5.0.6 on 2024-06-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tourcategory'),
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='backgroundMobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paquete.cloudinaryimage', verbose_name='Imagen de Fondo para Mobile'),
        ),
    ]
