# Generated by Django 5.0.6 on 2024-07-11 21:35

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallerycarousel_carouselbuttonname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='galleryIni',
            field=wagtail.fields.StreamField([('Tipo1', wagtail.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('carouselTitulo', wagtail.blocks.CharBlock(help_text='Titulo', max_length=75)), ('carouselDuracion', wagtail.blocks.CharBlock(help_text='Titulo', max_length=75)), ('carouselLink', wagtail.blocks.CharBlock(help_text='Link', max_length=200)), ('carouselButtonName', wagtail.blocks.CharBlock(help_text='texto del Boton', max_length=75))])), ('Tipo2', wagtail.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('carouselTitulo', wagtail.blocks.CharBlock(default=' ', help_text='Titulo', max_length=75)), ('carouselButtonName', wagtail.blocks.CharBlock(help_text='texto del Boton', max_length=75))]))], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inicio',
            name='formularioSubtitulo',
            field=models.CharField(max_length=200, verbose_name='Subtitulo Formulario'),
        ),
        migrations.DeleteModel(
            name='GalleryCarousel',
        ),
    ]
