# Generated by Django 5.0.6 on 2024-09-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_nosotros_puvname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='puvImage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage'),
            preserve_default=False,
        ),
    ]
