# Generated by Django 5.0.6 on 2024-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_nosotros_puvimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='mision',
            field=models.CharField(max_length=300, verbose_name='Mision'),
        ),
    ]
