# Generated by Django 5.0.6 on 2024-06-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='body',
        ),
    ]
