# Generated by Django 5.0.6 on 2024-07-20 20:56

import django.db.models.deletion
import home.models
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_inicio_galleryini_alter_inicio_formulariosubtitulo_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='certificadosSubtitle',
            field=models.CharField(default='TEST', max_length=100, verbose_name='Certificados Subtitilo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='partnersSubtitle',
            field=models.CharField(default='TEST', max_length=100, verbose_name='Partners Subtitilo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='valoresSubtitle',
            field=models.CharField(default='TEST', max_length=100, verbose_name='Valores Subtitilo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inicio',
            name='galleryIni',
            field=wagtail.fields.StreamField([('Tipo1', wagtail.blocks.StructBlock([('photo', home.models.MyImageChooserBlock(required=False)), ('carouselTitulo', wagtail.blocks.CharBlock(help_text='Titulo', max_length=75)), ('carouselDuracion', wagtail.blocks.CharBlock(help_text='Titulo', max_length=75)), ('carouselLink', wagtail.blocks.CharBlock(help_text='Link', max_length=200)), ('carouselButtonName', wagtail.blocks.CharBlock(help_text='texto del Boton', max_length=75)), ('miniPhotos', wagtail.blocks.ListBlock(home.models.MyImageChooserBlock(required=False)))])), ('Tipo2', wagtail.blocks.StructBlock([('photo', home.models.MyImageChooserBlock(required=False)), ('carouselTitulo', wagtail.blocks.CharBlock(default=' ', help_text='Titulo', max_length=75)), ('carouselButtonName', wagtail.blocks.CharBlock(help_text='texto del Boton', max_length=75))]))]),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('formTitle', models.CharField(max_length=100, verbose_name='Titulo del Formulario de Contacto')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Direccion de la Empresa')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
