# Generated by Django 5.0.6 on 2024-08-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_nosotros_certificadossubtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage', verbose_name='Imagen Icono'),
        ),
    ]
