# Generated by Django 5.0.6 on 2024-09-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_nosotros_vision_alter_nosotros_mision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='vision',
            field=models.CharField(max_length=350, verbose_name='Vision'),
        ),
    ]
