# Generated by Django 5.0.6 on 2024-08-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_informacion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='backgroundMobile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='subTitulo',
            field=models.CharField(default='gaaa', max_length=100, verbose_name='SubTitulo'),
            preserve_default=False,
        ),
    ]
