# Generated by Django 5.0.6 on 2024-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_nosotros_estadisticas_certificados_partners_valores'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='formularioSubtitulo',
            field=models.CharField(default='', max_length=75, verbose_name='Subtitulo Formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicio',
            name='formularioTitulo',
            field=models.CharField(default='', max_length=75, verbose_name='Titulo Formulario'),
            preserve_default=False,
        ),
    ]
