# Generated by Django 5.0.6 on 2024-06-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_inicio_formulariosubtitulo_inicio_formulariotitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycarousel',
            name='carouselDuracion',
            field=models.CharField(default='', max_length=30, verbose_name='Subtitulo Paquetes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycarousel',
            name='carouselTitulo',
            field=models.CharField(default='', max_length=50, verbose_name='Subtitulo Paquetes'),
            preserve_default=False,
        ),
    ]
