# Generated by Django 5.0.6 on 2024-06-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_gallerycarousel_carouselduracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNumeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numero', models.IntegerField(blank=True, verbose_name='Numero Celular')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='link')),
            ],
        ),
        migrations.AlterField(
            model_name='gallerycarousel',
            name='carouselDuracion',
            field=models.CharField(max_length=30, verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='gallerycarousel',
            name='carouselTitulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
