# Generated by Django 5.0.6 on 2024-08-20 23:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_salidaspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electronico')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='whatsapp')),
                ('youtube', models.CharField(max_length=255, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('tiktok', models.CharField(max_length=255, verbose_name='Tiktok')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelDataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('numero', models.CharField(max_length=255, verbose_name='Numero de Celular ')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='home.datageneral')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
