# Generated by Django 5.0.6 on 2024-08-31 04:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('home', '0011_datageneral_teldatageneral'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('articuloPrincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articuloPrincipal', to='blog.blog')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage')),
                ('backgroundMobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticulosRecomendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('articuloPrincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articuloPrincipalOrderable', to='blog.blog')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulosRecomendados', to='home.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
