# Generated by Django 5.0.6 on 2024-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_datanumeros_alter_gallerycarousel_carouselduracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanumeros',
            name='numero',
            field=models.CharField(max_length=255, verbose_name='Numero Formate +x xxxxxxx'),
        ),
    ]
