# Generated by Django 5.0.6 on 2024-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_datanumeros_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=255, verbose_name='Numero Formato +x xxxxxxx o Texto de Boton ')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='link')),
            ],
        ),
        migrations.DeleteModel(
            name='DataNumeros',
        ),
    ]
