# Generated by Django 5.0.6 on 2024-09-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blogpage_articulosrecomendados'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='midMessage',
            field=models.CharField(default='aoe', max_length=300, verbose_name='Mensaje Intermedio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='midMessageSubtitle',
            field=models.CharField(default='aoe', max_length=200, verbose_name='Mensaje Intermedio Subtitulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='mision',
            field=models.CharField(default='aoe', max_length=400, verbose_name='Mision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='puv',
            field=models.CharField(default='aoe', max_length=300, verbose_name='Promesa Unica de Valor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='puvImage',
            field=models.ForeignKey(default='aoe', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cloudinaryimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='puvName',
            field=models.CharField(default='aoe', max_length=100, verbose_name='Promesa Unica de Valor Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nosotros',
            name='vision',
            field=models.CharField(default='aoe', max_length=400, verbose_name='Vision'),
            preserve_default=False,
        ),
    ]
