# Generated by Django 5.0.6 on 2024-07-02 19:45

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0002_paquete_locale_paquete_translation_key'),
    ]

    operations = [
            BootstrapTranslatableModel('paquete.Paquete')
    ]
