# Generated by Django 5.0.6 on 2024-07-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0002_alter_dias_item_alter_excluidoitempaquete_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo del Dia'),
        ),
    ]
