# Generated by Django 5.0.6 on 2024-07-02 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0003_auto_20240702_1945'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={'verbose_name': 'paquete'},
        ),
        migrations.AlterField(
            model_name='paquete',
            name='locale',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paquete',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='paquete',
            unique_together={('translation_key', 'locale')},
        ),
    ]
