# Generated by Django 5.0.6 on 2024-07-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0004_alter_paquete_options_alter_paquete_locale_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
