# Generated by Django 5.0.6 on 2024-07-02 21:00

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0005_alter_paquete_locale_alter_paquete_translation_key'),
    ]

    operations = [
            BootstrapTranslatableModel('paquete.Paquete')
    ]
