# Generated by Django 5.0.6 on 2024-07-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0006_auto_20240702_2100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paquete',
            unique_together=set(),
        ),
    ]
