# Generated by Django 5.0.6 on 2024-07-02 21:06

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0007_alter_paquete_unique_together'),
    ]

    operations = [
            BootstrapTranslatableModel('paquete.Paquete')
    ]
