# Generated by Django 5.0.6 on 2024-07-02 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0008_auto_20240702_2106'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='paquete',
            unique_together={('translation_key', 'locale')},
        ),
    ]
