# Generated by Django 5.0.6 on 2024-07-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0009_alter_paquete_locale_alter_paquete_translation_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={},
        ),
    ]
